spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sonar
    username: root
    password: root
  activemq:
    broker-url:
  redis:
    host: 127.0.0.1


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名匹配规则

logging:
  level:
    com:
      wzj:
        cache:
          mapper: debug

debug: true
