server:
  port: 8082

spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://192.168.34.79:3306/local
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://192.168.34.79:3306/slaver
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://192.168.34.79:3306/slaver
      username: root   # 只读账户
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    cluster:
      clusterNodes: 127.0.0.1:6379 #,127.0.0.1:6380,127.0.0.1:6381 #192.168.2.10:9000,192.168.2.13:9001,192.168.2.14:9001
      commandTimeout: 1000
      expireSeconds: 1000
  jedis:
    database: 0
    pool:
      max-active: 1024
      max-wait: 20000
      max-idle: 200
      min-idle: 10
